### ISSUE TITLE
RFC: Remove Bumblebee support

### ISSUE THREAD

**Issue by ventureoo** [CachyOS/mhwd-db-cachyos#3]
Bumblebee is an obsolete way to run Optimus on NVIDIA. It is not officially supported by NVIDIA and does not make sense as of driver version 435+. Nevertheless, it may be necessary for users of the old 390 branch, but I suggest removing it as I believe it will bring more pain for the user than benefits.

Some remarks:
- No updates since 2013
- Has a lot of performance issues
- Much more difficult to use

It also does not make sense to support it when optimus-manager is available - a better alternative that supports GPU switching via acpi_call or with the same bbswitch (see https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options).

An alternative way for users is also to use only NVIDIA GPU, with power configuration using GWE/nvidia-smi (see https://wiki.archlinux.org/title/NVIDIA_Optimus#Use_NVIDIA_graphics_only).

**Comment by SoongVilda** [comment]
Bumblebee trash is not needed, I consider removing that.
